name: Build and deploy React app to Azure Web App

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: .

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build React app (ignore warnings)
        run: CI=false npm run build

      - name: Login to Azure
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: tkl-portfolio  # <-- Make sure this matches your Azure App name exactly
          slot-name: Production
          package: ./build
